version: "3.9"
networks:
  net1:
    name: net1
    driver: bridge
    
services:
  lb:
    build: ./lb/
    image: lb
    platform: linux/x86_64
    container_name: lb
    ports:
      - "5000:5000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    networks:
      net1:
        aliases:
          - lb

  server:
    build: ./server/
    image: server
    platform: linux/x86_64
    networks:
      net1:
        aliases:
          - server

  metadata:
    build: ./metadata/
    image: metadata
    platform: linux/x86_64
    container_name: metadata
    networks:
      net1:
        aliases:
          - metadata

  shardmanager:
    build: ./shardmanager/
    image: shardmanager
    platform: linux/x86_64
    container_name: shardmanager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    privileged: true
    networks:
      net1:
        aliases:
          - shardmanager

    